name: Norminette Check
run-name: Norminette check for ${{ github.event.pull_request.head.ref }}

on: 
  pull_request:
    branches:
      - main

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Norminette
        run: pip install norminette

      - name: Run Norminette and save output
        id: run_norminette
        run: |
          norminette > norminette_output.txt
          if [ $? -ne 0 ]; then
            echo "has_errors=true" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "has_errors=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Display Norminette Output
        run: cat norminette_output.txt

      - name: Check for Norminette Errors
        if: steps.run_norminette.outputs.has_errors == 'true'
        run: |
          echo "::error::Norminette found errors. Please check the output above."
          exit 1
        continue-on-error: false
